/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: a85603396e30a8e948caaed45152ebbc)
interface __BaseEnv_Env {
	KV: KVNamespace;
	ROOT_DOMAIN: "test.is-in.nz" | "is-in.nz";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		KV: KVNamespace;
		ROOT_DOMAIN: "test.is-in.nz";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
