name = "is-in-email-inbound"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "KV"
id = "779184d4ccd842dda9a33fb40845fa85"
preview_id = "2d733b8ee95746f6bdd3693ef2de6b7d"

[vars]
ROOT_DOMAIN = "is-in.nz"

[env.staging]
name = "is-in-email-inbound-staging"

[[env.staging.kv_namespaces]]
binding = "KV"
id = "f3578122d7424930ab2d78c34abdf22c"
preview_id = "f6d6ae7d37e44bb987df340aaebdd17b"

[env.staging.vars]
ROOT_DOMAIN = "test.is-in.nz"
