/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 41f6045ea5a5d56027eab703e25b59fe)
interface __BaseEnv_Env {
	KV: KVNamespace;
	ROOT_DOMAIN: "test.is-in.nz" | "is-in.nz";
	PRODUCT_NAME: "is-in.nz";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		KV: KVNamespace;
		ROOT_DOMAIN: "test.is-in.nz";
		PRODUCT_NAME: "is-in.nz";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
